services:
  nginx:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    depends_on:
      - auth-system
      - business-logic
      - feed-logic
      - media-response
  feed-content:
    image: trustartup.azurecr.io/feedcontent
    environment: 
      - ASPNETCORE_ENVIRONMENT=${DEBUG:-production}
      - ConnectionStrings__Database=host=feed-content-db;database=postgres;user id=postgres;password=postgres;
    ports:
      - "8081:80"
    depends_on:
      - feed-content-db
  feed-content-db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - feed-content-db:/var/lib/postgresql/data
  media-system:
    image: trustartup.azurecr.io/mediasystem
    environment:
      - ASPNETCORE_ENVIRONMENT=${DEBUG:-production}
      - ConnectionStrings__Database=host=media-system-db;database=postgres;user id=postgres;password=postgres;
    volumes:
      - media:/app/media
    ports:
      - "8083:80"
    depends_on:
      - media-system-db
  media-system-db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - media-system-db:/var/lib/postgresql/data
  business-content:
    image: trustartup.azurecr.io/businesscontent
    environment:
      - APP_ENV=${DEBUG:-production}
      - APP_KEY=yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
      - APP_DEBUG=${DEBUG:-false}
      - DB_CONNECTION=pgsql
      - DB_HOST=business-content-db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    command: ["/bin/sh", "-c", "php artisan migrate --force && /docker-entrypoint.sh"]
    ports:
      - "8086:80"
    depends_on:
      - business-content-db
  business-content-db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - business-content-db:/var/lib/postgresql/data
  user-system:
    image: trustartup.azurecr.io/usersystem
    environment:
      - APP_ENV=${DEBUG:-production}
      - APP_KEY=yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
      - APP_DEBUG=${DEBUG:-false}
      - DB_CONNECTION=pgsql
      - DB_HOST=user-system-db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    command: ["/bin/sh", "-c", "php artisan migrate --force --seed && /docker-entrypoint.sh"]
    ports:
      - "8084:80"
    depends_on:
      - user-system-db
  user-system-db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - user-system-db:/var/lib/postgresql/data
  rating-calculation-system:
    image: trustartup.azurecr.io/ratingcalculationsystem
    ports:
      - "8082:80"
  auth-system:
    image: trustartup.azurecr.io/authsystem
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=${DEBUG:-production}
      - APP_KEY=yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
      - APP_DEBUG=${DEBUG:-false}
      - API_USER=http://user-system
      - |
        PRIVATE_KEY=
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQBsAJJ+O3fTxnPlXCleUCLGleHad+0u/4P+qKoul2Sd49b6Ta/4
        OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBwVUDOG8E1VU8NDPN1/uSUz7+1yFO4
        DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGhVAZVhWdnJmRFcvBB98HoA2/x5Lkv
        78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi6kzPyVHI36mK0PcManhMBWQOupj1
        p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5PbjrUycVRhYZFM6wDYEMdooQR46Ie/
        tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2tAgMBAAECggEACjRDowmbWLb3XERI
        5FBN+NVQcYPDNR2PKxBkg+Jp70EHnr6YUaun88jJIdQ0Epj1H+NzEyTmpKnOmo9l
        TB30RajIZrDYoGFfBqyilBNxJV47jsFOp6U4tYaqOF37TOWW5x2y7ROuJGUTIjMy
        YRchQEzgDFR+YJCQCL/DU3hFKdaJ1UPko5IearZJmFHAik1KaXETXqj62+6qvlp0
        n1mat72Pa8N3xNwK/36v2oqJBy7hFPz/QlCAe6+Lx86Ujsf9mXWHWbCLyLOAJ3a+
        PcicbVhL5mVmMnL6VK5xqyO6mjYD76u1IcorRveq5a5Uc5wWkh4mskflbePcEvtM
        /OcJQQKBgQCvqsPtua00Kyu5npBI+aqPWlALP1f33qMQQUIzT8krc3ihxr6Rv6Yj
        MLsFSqZxPMjgqVkaR5xaF8fCtWu0+CqJ0i9046r4UW2xn0PJ+2+ttTbpiuQ7LIR5
        eZ1XPYhkcqDWhgY3VFuUXNe6MlBZmoNH5mDbqvinfzPRoI8qViFOswKBgQCdZFP7
        cVmnkxuyzmaN+BNaRNyXrUHjFIfHeWLd3urvspMbxCBu/Sj+RIRxC2yP6zBDu3SA
        sVwo59Iko6DP2ZuCIOoek6fh1qKMVrhvEXYU3rSvQ5x0KzksrTwzde1bxQY1ptOQ
        BtRKjR8saCOD3BRxXbwqzxbWAvF6Ha8ahzQSHwKBgQCuqMIf9lJBIX9bEk3xUNOF
        rs0RMcz8NY+51LjGndit7CSP7TSDY6MDMCtzKnLs+fvcbGScXYEWjrheXtWVXH2n
        BKWMueS++u9vAKR9ChNTCm9rq14be7rHsOSA3jxjaxmB0kYR8z0O+XTAu8/qF1fa
        QDQjlQ2gNDhIgDR4aqS5QwKBgGfZ6lwv17NtqsoZzKuCc+qNI2zlgmL+ifUB0E2L
        qENO9ihNCgWR/7l+plEc854m1mrqxp2f6aqIBC3u1c4vzJ9ZboGMdira/9hP5FRN
        FjgBFwHKP/KbDpe/Gsjt2BdEcqt2D4SqLOugIGChukVoMwj2i5FHoc7GlGU6Lu73
        JVGLAoGBAIHbIhy4W13R4m4suFgBc08O1Jgt0lLQWaQstnvESrr/6roBSo9p46n9
        rIfWWVD94phQVQz7sTAPD8HIGjsn3f2uZR/23O9/rOqdG5rj5y9TwZg3zAlVGB8E
        GLH1GOGjMdgyosxMyajWTxyJVhsRcdRl1fIoI0mGteK9V8NXJTLZ
        -----END RSA PRIVATE KEY-----
      - |
        PUBLIC_KEY=
        -----BEGIN PUBLIC KEY-----
        MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBsAJJ+O3fTxnPlXCleUCLG
        leHad+0u/4P+qKoul2Sd49b6Ta/4OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBw
        VUDOG8E1VU8NDPN1/uSUz7+1yFO4DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGh
        VAZVhWdnJmRFcvBB98HoA2/x5Lkv78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi
        6kzPyVHI36mK0PcManhMBWQOupj1p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5Pb
        jrUycVRhYZFM6wDYEMdooQR46Ie/tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2t
        AgMBAAE=
        -----END PUBLIC KEY-----
    ports:
      - "8087:80"
    depends_on:
      - user-system
  feed-logic:
    image: trustartup.azurecr.io/feedlogic
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=${DEBUG:-production}
      - Authentication__JwtRsaPublicKey=MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBsAJJ+O3fTxnPlXCleUCLGleHad+0u/4P+qKoul2Sd49b6Ta/4OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBwVUDOG8E1VU8NDPN1/uSUz7+1yFO4DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGhVAZVhWdnJmRFcvBB98HoA2/x5Lkv78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi6kzPyVHI36mK0PcManhMBWQOupj1p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5PbjrUycVRhYZFM6wDYEMdooQR46Ie/tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2tAgMBAAE=
      - Settings__FeedContentSystemUrl=http://feed-content
      - Settings__MediaSystemUrl=http://media-system
      - Settings__UserSystemUrl=http://user-system
      - Settings__PaymentSystemUrl=http://payment-system
    ports:
      - "8088:80"
    depends_on:
      - feed-content
      - user-system
      - media-system
      - payment-system
  media-response:
    image: trustartup.azurecr.io/mediaresponse
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=${DEBUG:-production}
      - Authentication__JwtRsaPublicKey=MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBsAJJ+O3fTxnPlXCleUCLGleHad+0u/4P+qKoul2Sd49b6Ta/4OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBwVUDOG8E1VU8NDPN1/uSUz7+1yFO4DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGhVAZVhWdnJmRFcvBB98HoA2/x5Lkv78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi6kzPyVHI36mK0PcManhMBWQOupj1p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5PbjrUycVRhYZFM6wDYEMdooQR46Ie/tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2tAgMBAAE=
      - Settings__MediaSystemUrl=http://media-system
    ports:
      - "8089:80"
    depends_on:
      - media-system
  business-logic:
    image: trustartup.azurecr.io/businesslogic
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=${DEBUG:-production}
      - APP_KEY=yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
      - APP_DEBUG=${DEBUG:-false}
      - API_BUSINESS_CONTENT=http://business-content
      - API_FEED_CONTENT=http://feed-content
      - API_MEDIA=http://media-system
      - API_USER=http://user-system
      - API_PAYMENT=http://payment-system
      - |
        PUBLIC_KEY=
        -----BEGIN PUBLIC KEY-----
        MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBsAJJ+O3fTxnPlXCleUCLG
        leHad+0u/4P+qKoul2Sd49b6Ta/4OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBw
        VUDOG8E1VU8NDPN1/uSUz7+1yFO4DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGh
        VAZVhWdnJmRFcvBB98HoA2/x5Lkv78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi
        6kzPyVHI36mK0PcManhMBWQOupj1p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5Pb
        jrUycVRhYZFM6wDYEMdooQR46Ie/tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2t
        AgMBAAE=
        -----END PUBLIC KEY-----
    ports:
      - "8090:80"
    depends_on:
      - user-system
      - business-content
      - media-system
      - feed-content
      - payment-system
  payment-system:
    image: trustartup.azurecr.io/paymentsystem
    environment:
      - APP_ENV=${DEBUG:-production}
      - APP_KEY=yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
      - APP_DEBUG=${DEBUG:-false}
      - DB_CONNECTION=pgsql
      - DB_HOST=payment-system-db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    command: ["/bin/sh", "-c", "php artisan migrate --force && /docker-entrypoint.sh"]
    ports:
      - "8091:80"
    depends_on:
      - payment-system-db
  payment-system-db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - payment-system-db:/var/lib/postgresql/data

volumes: 
  media:
  feed-content-db:
  media-system-db:
  business-content-db:
  user-system-db:
  payment-system-db:
